### ISSUE TITLE
Signon widget in Angular SSO sample not showing

### ISSUE THREAD

**Issue by jmichaud-ips** [jmelberg/angular-sso-samples#1]
Follow these steps to reproduce the problem.
1. Download the Angular-sso-samples repo.
2. Run the website project with visual studio
3. Make sure okta application is configured with port for redirect URI and CORS
4. Click "Try Me" button under Sign-in Widget
5. Login using widget
6. You should now see the home screen with token
7. Click Sign Out in the top right
8. Brings me back to Login page, I can see the widget
9. Change url in browser by deleting the word "login" to bring you to the home page
10. Click on the "Please sign in to continue" link to bring you back to login page
11. Widget is not displayed.

Was able to reproduce on Chrome and IE 11.

**Comment by jmelberg** [comment]
@jmichaud-ips: Thank you for discovering that. I removed the `widget` true/false toggle to eliminate this problem. Please pull the most recent version to verify it works with your use case.
